UI tests
vikuliyana/TeamCity-NoBugs pull request #2
Opened 2024-11-09 22:40 UTC by vikuliyana

**UI module with tests for Build Type**

Positive test "User should be able to create build configuration" with the next steps:
```
1. Login
2. Project creation on API level
3. Create build type
4. Check that the build type was created
5. Open build type page and check that title are the same as a build type name that was defined during creation
```

Negative test "User should not be able to create build configuration with an empty name" with the next steps:
```
1. Login
2. Project creation on API level
3. Create build type with an empty name
4. Check that the error message is shown
```

2024-11-10 20:42 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 20:42 UTC, nobugs-me commented on .idea/.gitignore
Папку .idea не нужно коммитить, так как в этой папке хранятся настройки твоей IDE - это часть может меняться от пользователя к пользователю, поэтому мы ее не "увековечиваем" в GIT.

2024-11-10 20:42 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +                .buildTypeNameValidationError.shouldHave(Condition.exactText("Build configuration name must not be empty"));
Также можно добавить на уровне API проверку, что build Type не создался.

2024-11-11 15:13 UTC, vikuliyana commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +                .buildTypeNameValidationError.shouldHave(Condition.exactText("Build configuration name must not be empty"));
Проверку добавила

2024-11-11 15:13 UTC, vikuliyana commented on .idea/.gitignore
Да, видимо случайно добавила :D

2024-11-11 15:26 UTC, vikuliyana commented
@nobugs-me Спасибо большое за ревью!
**Исправлено:**
1. Директорию .idea убрала
2. Добавила новые шаги по проверке числа конфигураций проекта до и после попытки создания с пустым именем в негативный тест кейс

2024-11-13 12:57 UTC, nobugs-me approved these changes
ривет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, поэтому Approve 🤝

2024-11-13 12:57 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +        var numberOfBuildTypesAfterTest = superUserCheckRequests.<Project>getRequest(PROJECTS).read("id:" + createdProject.getId()).getBuildTypes().getCount();
Все верно!

2024-11-13 13:27 UTC, merged